// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPO_1D6NFfUy_n5-eNU2W5N897EWqhNRo',
    appId: '1:1091486758779:web:3489caf932860710e86fde',
    messagingSenderId: '1091486758779',
    projectId: 'pharmas-a5c6d',
    authDomain: 'pharmas-a5c6d.firebaseapp.com',
    storageBucket: 'pharmas-a5c6d.appspot.com',
    measurementId: 'G-8M01MT0S6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyb9exYGYp5tjbiX5ag0aXq804nzLd1M',
    appId: '1:1091486758779:android:ee441f1682e04c85e86fde',
    messagingSenderId: '1091486758779',
    projectId: 'pharmas-a5c6d',
    storageBucket: 'pharmas-a5c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSNK1hw0FX4tl-cH7oY6cbd9Q4F8viVek',
    appId: '1:1091486758779:ios:a663869527486b33e86fde',
    messagingSenderId: '1091486758779',
    projectId: 'pharmas-a5c6d',
    storageBucket: 'pharmas-a5c6d.appspot.com',
    iosClientId:
        '1091486758779-lfpfq3r0so9tgnjcnq72389cpbrtvt1t.apps.googleusercontent.com',
    iosBundleId: 'a.gautham.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSNK1hw0FX4tl-cH7oY6cbd9Q4F8viVek',
    appId: '1:1091486758779:ios:a663869527486b33e86fde',
    messagingSenderId: '1091486758779',
    projectId: 'pharmas-a5c6d',
    storageBucket: 'pharmas-a5c6d.appspot.com',
    iosClientId:
        '1091486758779-lfpfq3r0so9tgnjcnq72389cpbrtvt1t.apps.googleusercontent.com',
    iosBundleId: 'a.gautham.eCommerce',
  );
}
